package hms.util;

import hms.billing.Bill;
import hms.model.Patient;
import hms.model.Doctor;
import hms.model.Appointment;

import java.io.FileOutputStream;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Utility class for generating PDF reports.
 * 
 * NOTE: This is a simplified text-to-PDF implementation.
 * For production use, integrate iText library:
 * - Add dependency: com.itextpdf:itext7-core
 * 
 * Current implementation creates formatted text files (can be converted to PDF).
 * Full iText implementation would provide professional PDF formatting.
 * 
 * @author HMS Team
 * @version 1.0
 */
public class PDFExporter {

    private static final String LINE_SEPARATOR = "═════════════════════════════════════════════════════════════";
    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    /**
     * Generates a patient report and saves to file.
     * 
     * @param patient the Patient object
     * @param outputPath file path to save the report
     * @throws IOException if file writing fails
     */
    public static void exportPatientReport(Patient patient, String outputPath) throws IOException {
        StringBuilder report = new StringBuilder();
        
        report.append(LINE_SEPARATOR).append("\n");
        report.append("                    PATIENT REPORT\n");
        report.append(LINE_SEPARATOR).append("\n\n");
        
        report.append("Generated: ").append(LocalDateTime.now().format(DATE_FORMAT)).append("\n\n");
        
        report.append("PATIENT INFORMATION:\n");
        report.append("─────────────────────────────────────────────────────────────\n");
        report.append("Patient ID: ").append(patient.getId()).append("\n");
        report.append("Name: ").append(patient.getName()).append("\n");
        report.append("Age: ").append(patient.getAge()).append(" years\n");
        report.append("Gender: ").append(patient.getGender()).append("\n");
        report.append("Phone: ").append(patient.getPhone()).append("\n");
        report.append("Address: ").append(patient.getAddress()).append("\n");
        
        report.append("\n").append(LINE_SEPARATOR).append("\n");
        report.append("Report generated by Hospital Management System (HMS)\n");
        report.append(LINE_SEPARATOR).append("\n");
        
        writeToFile(report.toString(), outputPath);
    }

    /**
     * Generates a billing report and saves to file.
     * 
     * @param bill the Bill object
     * @param patient the associated Patient
     * @param outputPath file path to save the report
     * @throws IOException if file writing fails
     */
    public static void exportBillingReport(Bill bill, Patient patient, String outputPath) throws IOException {
        StringBuilder report = new StringBuilder();
        
        report.append(LINE_SEPARATOR).append("\n");
        report.append("                    BILLING REPORT\n");
        report.append(LINE_SEPARATOR).append("\n\n");
        
        report.append("Generated: ").append(LocalDateTime.now().format(DATE_FORMAT)).append("\n\n");
        
        report.append("PATIENT INFORMATION:\n");
        report.append("─────────────────────────────────────────────────────────────\n");
        report.append("Patient ID: ").append(patient.getId()).append("\n");
        report.append("Patient Name: ").append(patient.getName()).append("\n");
        report.append("Phone: ").append(patient.getPhone()).append("\n\n");
        
        report.append("BILL DETAILS:\n");
        report.append("─────────────────────────────────────────────────────────────\n");
        report.append("Bill ID: ").append(bill.getBillId()).append("\n");
        report.append("Total Amount: $").append(String.format("%.2f", bill.getTotalAmount())).append("\n");
        report.append("Paid Amount: $").append(String.format("%.2f", bill.getPaidAmount())).append("\n");
        report.append("Remaining: $").append(String.format("%.2f", bill.getTotalAmount() - bill.getPaidAmount())).append("\n");
        report.append("Status: ").append(bill.isPaid() ? "PAID" : "PENDING").append("\n");
        
        report.append("\nBill Items:\n");
        report.append("─────────────────────────────────────────────────────────────\n");
        for (var item : bill.getBillItems()) {
            report.append(item.getDescription()).append(": $").append(String.format("%.2f", item.getCost())).append("\n");
        }
        
        report.append("\n").append(LINE_SEPARATOR).append("\n");
        report.append("Report generated by Hospital Management System (HMS)\n");
        report.append(LINE_SEPARATOR).append("\n");
        
        writeToFile(report.toString(), outputPath);
    }

    /**
     * Generates an appointment report and saves to file.
     * 
     * @param appointment the Appointment object
     * @param patient the associated Patient
     * @param doctor the associated Doctor
     * @param outputPath file path to save the report
     * @throws IOException if file writing fails
     */
    public static void exportAppointmentReport(Appointment appointment, Patient patient, Doctor doctor, String outputPath) throws IOException {
        StringBuilder report = new StringBuilder();
        
        report.append(LINE_SEPARATOR).append("\n");
        report.append("                    APPOINTMENT REPORT\n");
        report.append(LINE_SEPARATOR).append("\n\n");
        
        report.append("Generated: ").append(LocalDateTime.now().format(DATE_FORMAT)).append("\n\n");
        
        report.append("APPOINTMENT DETAILS:\n");
        report.append("─────────────────────────────────────────────────────────────\n");
        report.append("Appointment ID: ").append(appointment.getAppointmentId()).append("\n");
        report.append("Date & Time: ").append(appointment.getDateTime().format(DATE_FORMAT)).append("\n");
        report.append("Status: ").append(appointment.getStatus()).append("\n\n");
        
        report.append("PATIENT INFORMATION:\n");
        report.append("─────────────────────────────────────────────────────────────\n");
        report.append("Name: ").append(patient.getName()).append("\n");
        report.append("ID: ").append(patient.getId()).append("\n");
        report.append("Phone: ").append(patient.getPhone()).append("\n\n");
        
        report.append("DOCTOR INFORMATION:\n");
        report.append("─────────────────────────────────────────────────────────────\n");
        report.append("Name: ").append(doctor.getName()).append("\n");
        report.append("Specialization: ").append(doctor.getSpecialization()).append("\n");
        report.append("Consultation Fee: $").append(String.format("%.2f", doctor.getConsultationFee())).append("\n\n");
        
        if (!appointment.getNotes().isEmpty()) {
            report.append("NOTES:\n");
            report.append("─────────────────────────────────────────────────────────────\n");
            report.append(appointment.getNotes()).append("\n");
        }
        
        report.append("\n").append(LINE_SEPARATOR).append("\n");
        report.append("Report generated by Hospital Management System (HMS)\n");
        report.append(LINE_SEPARATOR).append("\n");
        
        writeToFile(report.toString(), outputPath);
    }

    /**
     * Writes content to a file.
     * 
     * @param content the content to write
     * @param filePath the file path
     * @throws IOException if writing fails
     */
    private static void writeToFile(String content, String filePath) throws IOException {
        try (FileOutputStream fos = new FileOutputStream(filePath)) {
            fos.write(content.getBytes());
            fos.flush();
        }
    }

    /**
     * Generates a sample system report.
     * 
     * @param totalPatients number of patients
     * @param totalDoctors number of doctors
     * @param totalAppointments number of appointments
     * @param outputPath file path to save the report
     * @throws IOException if file writing fails
     */
    public static void exportSystemReport(int totalPatients, int totalDoctors, int totalAppointments, String outputPath) throws IOException {
        StringBuilder report = new StringBuilder();
        
        report.append(LINE_SEPARATOR).append("\n");
        report.append("                HOSPITAL SYSTEM REPORT\n");
        report.append(LINE_SEPARATOR).append("\n\n");
        
        report.append("Generated: ").append(LocalDateTime.now().format(DATE_FORMAT)).append("\n\n");
        
        report.append("SYSTEM STATISTICS:\n");
        report.append("─────────────────────────────────────────────────────────────\n");
        report.append("Total Patients: ").append(totalPatients).append("\n");
        report.append("Total Doctors: ").append(totalDoctors).append("\n");
        report.append("Total Appointments: ").append(totalAppointments).append("\n");
        
        report.append("\n").append(LINE_SEPARATOR).append("\n");
        report.append("Report generated by Hospital Management System (HMS)\n");
        report.append(LINE_SEPARATOR).append("\n");
        
        writeToFile(report.toString(), outputPath);
    }
}
